# Generated by Django 4.2.22 on 2025-06-09 23:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biomarkers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarkercategory',
            name='default_acceptable_range',
            field=models.FloatField(blank=True, help_text='Default acceptable deviation from target value (±)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='biomarkercategory',
            name='default_target_value',
            field=models.FloatField(blank=True, help_text='Default target value for this biomarker', null=True),
        ),
        migrations.CreateModel(
            name='UserBiomarkerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField(help_text='Your target value for this biomarker')),
                ('acceptable_range', models.FloatField(help_text='Acceptable deviation from target value (±)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomarkers.biomarkercategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
