# Generated by Django 4.2.22 on 2025-06-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomarkers', '0002_biomarkercategory_default_acceptable_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomarkercategory',
            name='default_acceptable_range',
        ),
        migrations.RemoveField(
            model_name='biomarkercategory',
            name='default_target_value',
        ),
        migrations.AddField(
            model_name='biomarkercategory',
            name='target_value',
            field=models.FloatField(blank=True, help_text='Optional target value for this biomarker (within reference range)', null=True),
        ),
        migrations.DeleteModel(
            name='UserBiomarkerTarget',
        ),
    ]
